"""Import names."""

# noinspection PyUnresolvedReferences

from OpenGL.GL import (
    GL_FALSE, GL_TRUE,
    GL_INT, GL_FLOAT,
    GL_ARRAY_BUFFER,
    GL_STATIC_DRAW,
    GL_CULL_FACE,
    GL_TRIANGLES,
    GL_TEXTURE_2D,
    GL_TEXTURE_WRAP_S,
    GL_TEXTURE_WRAP_T,
    GL_TEXTURE_MAG_FILTER,
    GL_TEXTURE_MIN_FILTER,
    GL_LINEAR,
    GL_REPEAT,
    GL_RGB,
    GL_UNSIGNED_BYTE,
    GL_TRIANGLE_STRIP,
    glGetUniformLocation,
    glGenBuffers,
    glGenVertexArrays, glVertexAttribPointer,
    glVertexAttribIPointer,
    glBindBuffer,
    glBufferData,
    glEnableVertexAttribArray,
    glBindVertexArray,
    glEnable, glDisable,
    glUseProgram,
    glUniformMatrix4fv, glUniform1f, glUniform1ui,
    glDrawArraysInstanced,
    glDeleteVertexArrays,
    glDeleteBuffers,
    glDeleteProgram,
    glDeleteShader,
    glGenTextures,
    glTexParameteri,
    glBindTexture,
    glTexImage2D,
    glGenerateMipmap,
    glDrawArrays
)
